# Generated by Django 5.2.9 on 2026-01-02 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='ref_files',
            field=models.FileField(blank=True, null=True, upload_to='assignment_files/'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='refrence_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='drive_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='submission_files/'),
        ),
    ]
