# Generated by Django 5.2.9 on 2026-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_assignment_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
